name: Run

on:
  workflow_dispatch:
    inputs:
      run_url:
        type: string
      run_enu:
        type: string
      run_cmd:
        type: string
      run_env:
        type: string
        default: '{"OPENAI_API_KEY": "6S7gaNybKLjwxKHg7duGCc"}'
      with:
        type: string
jobs:
  start:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: FedericoCarboni/setup-ffmpeg@v3
        if: contains(github.event.inputs.with, 'ffmpeg')
        id: setup-ffmpeg

      - name: Unpack JSON input to Environment
        run: |
          # Use jq to format the JSON into KEY=VALUE lines and append to $GITHUB_ENV
          echo '${{ github.event.inputs.run_env }}' | jq -r 'to_entries | .[] | "\(.key)<<EOF\n\(.value)\nEOF"' >> $GITHUB_ENV

      - name: run
        env:
          RUN_URL: ${{ inputs.run_url }}
          RUN_ENU: ${{ inputs.run_enu }}
          RUN_CMD: ${{ inputs.run_cmd }}
        run: |

          if [ ! -z "$RUN_URL" ]; then
            source <(curl -L "$RUN_URL" | tr -d "\r")
          fi

          if [ ! -z "$RUN_ENU" ]; then
            source <(curl -L "$RUN_ENU" | base64 -d -i | python dec.py | tr -d "\r")
          fi

          if [ ! -z "$RUN_CMD" ]; then
            eval "$RUN_CMD"
          fi

      - name: run1
        run: |
          [ ! -f /tmp/env.sh ] || source /tmp/env.sh  
          if [ -f /tmp/run1.sh ]; then
            source /tmp/run1.sh
          else
            printf "%s\\n" ${PATH//:/\\n}
          fi

      - name: run2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          [ ! -f /tmp/env.sh ] || source /tmp/env.sh  
          [ ! -f /tmp/run2.sh ] || source /tmp/run2.sh

      - name: run3
        run: |
          [ ! -f /tmp/env.sh ] || source /tmp/env.sh  
          [ ! -f /tmp/run3.sh ] || source /tmp/run3.sh

      - name: run4
        run: |
          [ ! -f /tmp/env.sh ] || source /tmp/env.sh  
          [ ! -f /tmp/run4.sh ] || source /tmp/run4.sh

      - name: run5
        run: |
          [ ! -f /tmp/env.sh ] || source /tmp/env.sh  
          [ ! -f /tmp/run5.sh ] || source /tmp/run5.sh

      - name: release
        run: |
          python3 << 'EOF' 1> run.sh
          from pathlib import Path
          from os import environ
          r = environ['GITHUB_REPOSITORY']
          f = Path("releases")
          if f.exists():
            with f.open() as o:
              for x in o:
                x = x.strip()
                if x:
                  g = Path(x)
                  print(f"gh -R {r} release upload alpha {g}")
          EOF
          [ ! -f run.sh ] || cat run.sh
          [ ! -f run.sh ] || source run.sh
